# https://golangci-lint.run/usage/configuration/
version: "2"
linters:
  default: standard
  enable:
    # https://github.com/go-critic/go-critic
    - gocritic
    # https://github.com/mgechev/revive
    - revive
    # https://github.com/mdempsky/unconvert
    - unconvert
    # https://github.com/mvdan/unparam
    - unparam
  settings:
    revive:
      rules:
        - name: var-naming
          disabled: true
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
