# https://golangci-lint.run/usage/configuration/
version: "2"
linters:
  default: standard
  enable:
    - gocritic
    - testifylint
    - unconvert
    - unparam
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
