# https://vektra.github.io/mockery/v2.51/configuration/

# Settings to avoid deprecation warnings
with-expecter: true
resolve-type-alias: false
issue-845-fix: true

# Set output directory for the mocks
dir: "mocks/mocks_{{.PackageName}}"

# Set package name for the mocks
outpkg: "mocks_{{.PackageName}}"

packages:
  # Generate mocks for interface(s) in the abstraction package
  github.com/huangsam/go-trial/pkg/abstraction:
    interfaces:
      UserRepository:
