# https://vektra.github.io/mockery/v2.51/configuration/

# Settings to avoid deprecation warnings
with-expecter: true
resolve-type-alias: false
issue-845-fix: true

# Settings for mock layout
dir: "mock/{{.PackageName}}"
outpkg: "{{.PackageName}}_mock"

packages:
  # Generate mocks for interface(s) in the abstraction package
  github.com/huangsam/go-trial/pkg/abstraction:
    interfaces:
      UserRepository:
