# https://vektra.github.io/mockery/v2.51/configuration/

# Generate EXPECT() methods for the mocks
with-expecter: true

# Set the output directory for the mocks
dir: "mocks/mocks_{{.PackageName}}"

# Set the package name for the mocks
outpkg: "mocks_{{.PackageName}}"

# Fix warnings from mockery CLI
resolve-type-alias: false
issue-845-fix: true

packages:
  # Generate mocks for interface(s) in the abstraction package
  github.com/huangsam/go-trial/pkg/abstraction:
    interfaces:
      UserRepository:
