name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  go-build:
    name: Go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Setup tools
        run: bash ./setup.sh ci
      - name: Run tests
        run: bash ./test.sh
      - name: Run build
        run: bash ./build.sh
